---
- name: Update APT package cache (equivalent to apt-get update)
  apt:
    update_cache: yes
    cache_valid_time: 3600  # Optional: cache is considered valid for 1 hour
    
- name: Set hostname on hosts
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Install common Dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - gnupg2
    - net-tools
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: Disable swap on all hosts and remove swap entry from /etc/fstab
  ansible.builtin.shell: |
    swapoff -a
    sed -i '/swap/d' /etc/fstab
  register: swap_off_result
  changed_when: "'swapoff' in swap_off_result.stdout or 'sed' in swap_off_result.stdout"
  check_mode: false
  ignore_errors: true

- name: Set Timezone
  ansible.builtin.timezone:
    name: "{{ timezone }}"
