---
- name: Install Argo CD
  shell: |
    kubectl create namespace argocd
    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

- name: Wait for Argo CD Server to be Ready
  shell: |
    kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=argocd-server -n argocd --timeout=120s

- name: Patch Argo CD Server Service to NodePort
  shell: "kubectl patch svc argocd-server -n argocd -p '{\"spec\": {\"type\": \"NodePort\"}}'"


- name: Get NodePort of Argo CD Server
  shell: kubectl get svc argocd-server -n argocd -o jsonpath='{.spec.ports[0].nodePort}'
  register: argocd_server_nodeport

- debug:
    var: argocd_server_nodeport.stdout

- name: Retrieve Argo CD Admin Initial Password
  shell: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
  register: argocd_admin_password

- debug:
    var: argocd_admin_password.stdout
