---
all:
  hosts:
  children:
    master:
      hosts:
        master-1:
          ansible_host: 10.80.24.63
          ansible_user: root
          ansible_ssh_pass: admin
          hostname: master-1
        master-2:
          ansible_host: 10.80.24.64
          ansible_user: root
          ansible_ssh_pass: admin
          hostname: master-2
        master-3:
          ansible_host: 10.80.24.65
          ansible_user: root
          ansible_ssh_pass: admin
          hostname: master-3
    worker:
      hosts:
        worker-1:
          ansible_host: 10.80.24.131
          ansible_user: root
          ansible_ssh_pass: admin
          hostname: worker-1
        worker-2:
          ansible_host: 10.80.24.132
          ansible_user: root
          ansible_ssh_pass: admin
          hostname: worker-2
    haproxy:
      hosts:
        haproxy-1:
          ansible_host: 10.80.24.141
          ansible_user: root
          ansible_ssh_pass: admin
          hostname: haproxy-1
          keepalived_interface: eth1
          keepalived_state: MASTER
          keepalived_priority: 100
        haproxy-2:
          ansible_host: 10.80.24.142
          ansible_user: root
          ansible_ssh_pass: admin
          hostname: haproxy-2
          keepalived_interface: eth1
          keepalived_state: BACKUP
          keepalived_priority: 99