---
- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'

- name: Execute Helm install script
  command: /tmp/get_helm.sh

- name: Verify Helm installation
  command: helm version
  register: helm_version
  failed_when: "'version' not in helm_version.stdout"

- debug:
    var: helm_version.stdout