- name: add Kubernetes apt-key for Kubernetes v1.29
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring-v1.29.asc
    mode: '0644'

- name: Add Kubernetes v1.29 repository
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring-v1.29.asc] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /'
    state: present
    filename: kubernetes-1.29

- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes